### ISSUE TITLE
KML files with only one polygon, are loaded as a linestring instead of a polygon 

### ISSUE THREAD

**Issue by kiks73** [phayes/geoPHP#120]
Running this code, I get a LineString element, but I expected to get a Polygon element.
If I duplicate the `Placemark` tag content, both Polygons are loaded correctly.

```
$geom = geoPHP::load($kml_string,'kml');
$geo_arr = $geom->getComponents();
for ($i=0; $i < count($geo_arr); $i++) {
	echo $geo_arr[$i]->geometryType();
}

```
Output is: LineString, but the KML file contains a Polygon!
```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
<Document>
	<name>GC.kmz</name>
	<Style id="sn_ylw-pushpin2">
		<IconStyle>
			<scale>1.1</scale>
			<Icon>
				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>
			</Icon>
			<hotSpot x="20" y="2" xunits="pixels" yunits="pixels"/>
		</IconStyle>
		<PolyStyle>
			<color>ff000000</color>
		</PolyStyle>
	</Style>
	<Style id="sh_ylw-pushpin19">
		<IconStyle>
			<scale>1.3</scale>
			<Icon>
				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>
			</Icon>
			<hotSpot x="20" y="2" xunits="pixels" yunits="pixels"/>
		</IconStyle>
		<PolyStyle>
			<color>ff000000</color>
		</PolyStyle>
	</Style>
	<StyleMap id="msn_ylw-pushpin13">
		<Pair>
			<key>normal</key>
			<styleUrl>#sn_ylw-pushpin2</styleUrl>
		</Pair>
		<Pair>
			<key>highlight</key>
			<styleUrl>#sh_ylw-pushpin19</styleUrl>
		</Pair>
	</StyleMap>
	<Folder>
		<name>GC</name>
		<Placemark>
			<name>GC</name>
			<styleUrl>#msn_ylw-pushpin13</styleUrl>
			<Polygon>
				<tessellate>1</tessellate>
				<outerBoundaryIs>
					<LinearRing>
						<coordinates>
							13.04705297936604,43.65223023935494,0 13.0478302208073,43.65225778933826,0 13.0478531067812,43.6528036119153,0 13.04701870770081,43.65278157777255,0 13.04705297936604,43.65223023935494,0 
						</coordinates>
					</LinearRing>
				</outerBoundaryIs>
			</Polygon>
		</Placemark>
	</Folder>
</Document>
</kml>

```

**Comment by BathoryPeter** [comment]
From OGC specification:
"The boundary of a Polygon consists of a set of LinearRings that make up its exterior and interior boundaries;"

LinearRing can be represented as a closed LineString therefore the components of Polygon will be LineStrings.

**Comment by kiks73** [comment]
I understand, but what I have to do if I need an simple "surface" and not a linestring?
What am I missing?

**Comment by BathoryPeter** [comment]
What would you do with it?

**Comment by kiks73** [comment]
I'm importing a kml file in mySql spatial.
I need surfaces to obatain spatial intersection between areas from different kml files.

**Comment by BathoryPeter** [comment]
Why don't you load Polygons to mysql?
INSERT ... GeomFromText(\' GeoPhp::load($kml)->out('wkt') \')

**Comment by kiks73** [comment]
That's what I'm doing. But I think I've found my error:

$geo_arr = $geom->getComponents();
for ($i=0; $i < count($geo_arr); $i++) {
	$el = $geo_arr[$i]->out('wkt');
        ....
        ... INSERT geomfromtext('$el') ...
}

I suppose that getComponents does not return the single geometry, if there is only one and not a geometry collection. Isn't it?

**Comment by BathoryPeter** [comment]
No, in GeoPhp component means the sub-geometries from which the geometry consists of. For example the components of a LineString are Points, and the components of MultiLinestring are LineStrings.

Btw, GeoPhp::load($kml)->out('wkt') with your kml results this:
```POLYGON ((13.04705297936604 43.65223023935494, 13.0478302208073 43.65225778933826, 13.0478531067812 43.6528036119153, 13.04701870770081 43.65278157777255, 13.04705297936604 43.65223023935494))```
Isn't it what you want?

**Comment by kiks73** [comment]
Yes now it is clear:
when kml contains a single polygon I have not to call $geom->getComponents(), on the contrary, when kml contains more than one polygon, I need to call $geom->getComponents() and import each element.
Thanks
