### ISSUE TITLE
Undefined offset 1 in WKT.class.php

### ISSUE THREAD

**Issue by AlanRochford** [phayes/geoPHP#121]
```
$app->map ( "/linestring/(:id)", function ($elementID = null) use ($app){
	
 	$body = $app->request->getBody (); // get the body of the HTTP request (from client)
	$geom = geoPHP::load("LINESTRING(1 1,5 1,5 5,1 5,1 1, 4326)");
	//$insert_string = pg_escape_bytea($geom->out('ewkb'));
	//$sql = "INSERT INTO PATHS (geom) values (ST_GeomFromWKB('$insert_string'))";
	$sql = "INSERT INTO PATHS (geom) values ($geom)";
	try {
		$db = getDB();
		$stmt =   pg_query($db, $sql);
		$db = null;
		echo 'Working';
	} 
	
	catch(PDOException $e) {
		//error_log($e->getMessage(), 3, '/var/tmp/phperror.log'); //Write error log
		echo '{"error":{"text":'. $e->getMessage() .'}}';
	}
} )->via( "POST");
```

Hi,

I am using the code above to try and insert a LINESTRING into my DB and get the undefined offset error. Has anyone else come across this issue and if so is there a fix for it.

Cheers,

Alan

**Comment by swen100** [comment]
Your error is in the linestring-definition:
$geom = geoPHP::load("LINESTRING(1 1,5 1,5 5,1 5,1 1**, 4326**)");

that should be correct:
$geom = geoPHP::load("LINESTRING(1 1,5 1,5 5,1 5,1 1), 4326");
or this one:
$geom = geoPHP::load("LINESTRING(1 1,5 1,5 5,1 5,1 1)", 4326);
try out both, one should work :)

**Comment by AlanRochford** [comment]
Thanks a lot man.

However I'm now getting an issue on the line below
`$sql = "INSERT INTO PATHS (geom) values ($geom)";`

It's saying that  Object of class LineString could not be converted to string. I don't really understand it as I don't see why it has to be converted to a string when the geom column in the database is of type Linestring
