### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by dalin-** [phayes/geoPHP#144]
Looks like the last release was 2.5yrs ago, and since then there've been about 10 bug fixes.  I'm assuming one of them is required by the Drupal [GeoField](https://www.drupal.org/project/geofield) module, since it requires master.  This means that it will end up as a git submodule.  Submodules aren't allowed on some hosts (namely [Pantheon](https://pantheon.io/docs/git-faq/#does-pantheon-support-git-submodules)).  Any chance that we could get a new release?

**Comment by gsolak** [comment]
@dalin-  what is your current deployment process? Can you use a forked repository?

**Comment by dalin-** [comment]
@gsolak 

phayes/geoPHP is required in this composer file:
http://cgit.drupalcode.org/geofield/tree/composer.json?h=8.x-1.x

So I think the maintainers of that project would need to fork phayes/geoPHP, then register that fork at Packagist, then update the composer file to use the new Packagist package.  (I'm no Composer expert, so feel free to let me know if there's a better way.)  That sounds like it could cause a fair bit of confusion, and split the efforts of the community.  

Is there some objection to rolling a new release?  Or is there some incomplete new feature that's blocking it?

**Comment by darvanen** [comment]
@gsolak I would also like to know if there is any progress towards a new release for the reasons @dalin- describes.

**Comment by patrickbussmann** [comment]
We can use https://github.com/swen100/geoPHP as I will do now 👍

**Comment by dalin-** [comment]
In summary, you can do something with [aliases](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias) to work around this.

**Comment by dalin-** [comment]
In summary, you can do something with [aliases](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias) to work around this.
