### ISSUE TITLE
Intersects, Crosses, Contains not working

### ISSUE THREAD

**Issue by e1sep0** [phayes/geoPHP#171]
Hello, i try to check, if 2 Geometry crosses or overlaps. I get one Polygon and one Collection of Polygons. I tried to check all collection and every polygon with first polygon, but result is false. 
I tried intersect, overlaps, crosses, contains, covers, coveredBy, touches options, but all results are false (  
I drawed theese polygons on map. There one polygon in another. How can i check this? Thank 
 you!
![image](https://user-images.githubusercontent.com/5094299/70992544-fb578e00-20da-11ea-9461-c24ae8e908cb.png)
![image](https://user-images.githubusercontent.com/5094299/70992592-10342180-20db-11ea-93cf-6dfa55a3517f.png)

**Comment by BathoryPeter** [comment]
These methods only works if GEOS is installed.
See the Advanced Methods chapter in the [API docs](https://geophp.net/api.html).

**Comment by e1sep0** [comment]
GEOS is installed, other polygons work fine, but if one polygon in another i get false on all functions

**Comment by e1sep0** [comment]
I have updated libgeos and got new error:
`TopologyException: side location conflict at 55.400816770953284 36.352091380312601`
But i have no such coordinates. Help please, how to fix this problem? Thank you

**Comment by e1sep0** [comment]
Problem was solved, when i divided GeometryCollection on several polygons and checked intersects of every polygon. Checking intersecting polygon with GeometryCOllection caused Exception.
