### ISSUE TITLE
Simplifying a Polygon fails

### ISSUE THREAD

**Issue by HendrikN** [phayes/geoPHP#24]
I'm trying to simplify a WKT-polygon using:

``` PHP
    $oGeometry = geoPHP::load($sWkt,'wkt');    
    $reducedGeom = $oGeometry->simplify(1.5);
    $sWkt = $reducedGeom->out('wkt');
```

PHP throws a fatal error:

```
Warning: fread() [function.fread]: Length parameter must be greater than 0 in WKB.class.php on line 71


Fatal error: Uncaught exception 'Exception' with message 'Linestring with less than two points' in LineString.class.php:35 Stack trace: 
#0 /adapters/WKB.class.php(81): LineString->__construct(Array) 
#1 /adapters/WKB.class.php(91): WKB->getLinstring(Resource id #69) 
#2 /adapters/WKB.class.php(49): WKB->getPolygon(Resource id #69) 
#3 /adapters/WKB.class.php(33): WKB->getGeometry(Resource id #69) 
#4 [internal function]: WKB->read('010300000001000...', true) 
#5 geophp/geoPHP.inc(53): call_user_func_array(Array, Array) 
#6 geophp/geoPHP.inc(107): geoPHP::load('010300000001000...', 'wkb', true) 
#7 parsewfs.php(65): geoPHP::geosTo in /geometry/LineString.class.php on line 35
```

Any ideas how to fix this? Simplifying the geomtry by 0 works (although obviously, it has no effect).

Thanks for your help

**Comment by iamginpy** [comment]
cant simplify this one. this is sandiego city POLYGON ((-98.2501459 27.751617, -98.2500949 27.751855, -98.2498929 27.752822, -98.2498189 27.752976, -98.2495739 27.75289, -98.2483579 27.752464, -98.2479529 27.752322, -98.2479149 27.752458, -98.2478039 27.752866, -98.2477669 27.753003, -98.2474749 27.753965, -98.2473509 27.754377, -98.2470789 27.755278, -98.2468759 27.755948, -98.2459739 27.755664, -98.2450149 27.755363, -98.2448389 27.75588, -98.2446509 27.756435, -98.2445559 27.756716, -98.2438089 27.756598, -98.2437589 27.756591, -98.2435459 27.757038, -98.2434329 27.757209, -98.2430949 27.757724, -98.2429829 27.757896, -98.2429209 27.758089, -98.2427369 27.75867, -98.2426759 27.758864, -98.2425839 27.759276, -98.2424559 27.759851, -98.2431169 27.759701, -98.2435299 27.759608, -98.2439049 27.759477, -98.2439329 27.759468, -98.2444569 27.75843, -98.2446369 27.758076, -98.2447239 27.757746, -98.2448249 27.75737, -98.2454569 27.75739, -98.2457979 27.757402, -98.2463139 27.757407, -98.2478649 27.757425, -98.2480759 27.757428, -98.2482819 27.757655, -98.2483159 27.757686, -98.2484199 27.757779, -98.2484549 27.757811, -98.2484599 27.757782, -98.2484749 27.757695, -98.2484799 27.757666, -98.2485539 27.757682, -98.2486039 27.75771, -98.2487579 27.757864, -98.2488639 27.757985, -98.2489319 27.758177, -98.2489439 27.758282, -98.2489439 27.758419, -98.2489119 27.758628, -98.2488519 27.75903, -98.2487959 27.759228, -98.2485989 27.759762, -98.2484689 27.759949, -98.2483199 27.760087, -98.2481599 27.760159, -98.2480789 27.760203, -98.2480169 27.760252, -98.2479679 27.760368, -98.2478199 27.760627, -98.2477269 27.761017, -98.2476649 27.761336, -98.2476839 27.761727, -98.2476869 27.761737, -98.2477149 27.761821, -98.2478509 27.762052, -98.2478819 27.76214, -98.2479379 27.762541, -98.2480199 27.762846, -98.2478639 27.76331, -98.2473969 27.764702, -98.2472419 27.765167, -98.2471769 27.765374, -98.2469839 27.765998, -98.2469209 27.766206, -98.2466439 27.767081, -98.2458149 27.769705, -98.2455389 27.770581, -98.2454329 27.77093, -98.2451179 27.771979, -98.2450139 27.772329, -98.2448919 27.772713, -98.2446319 27.773531, -98.2444639 27.773492, -98.2402729 27.77253, -98.2388759 27.77221, -98.2381849 27.772033, -98.2361139 27.771502, -98.2354239 27.771325, -98.2352279 27.771274, -98.2346399 27.771124, -98.2344449 27.771074, -98.2327919 27.770655, -98.2285769 27.769589, -98.2284849 27.769558, -98.2286909 27.769001, -98.2287169 27.76893, -98.2293079 27.767331, -98.2295239 27.766852, -98.2301749 27.765414, -98.2303919 27.764936, -98.2304269 27.764832, -98.2305349 27.76452, -98.2305719 27.764417, -98.2305959 27.764344, -98.2306119 27.7643, -98.2306629 27.764125, -98.2306849 27.764052, -98.2307029 27.763991, -98.2307409 27.763871, -98.2309149 27.763332, -98.2309399 27.763255, -98.2309769 27.763154, -98.2309689 27.762965, -98.2312019 27.762332, -98.2312879 27.762209, -98.2313129 27.762133, -98.2313919 27.761905, -98.2314179 27.76183, -98.2310749 27.761956, -98.2307489 27.762077, -98.2300249 27.761897, -98.2296709 27.761809, -98.2295479 27.761785, -98.2298649 27.760178, -98.2307449 27.755737, -98.2309459 27.755786, -98.2314829 27.755919, -98.2325089 27.756173, -98.2331939 27.756344, -98.2334799 27.755545, -98.2334959 27.755502, -98.2328769 27.75525, -98.2328079 27.755222, -98.2324009 27.755085, -98.2310759 27.75502, -98.2305599 27.754996, -98.2305819 27.754666, -98.2305919 27.754543, -98.2312679 27.75438, -98.2313289 27.754338, -98.2316599 27.754116, -98.2318929 27.753995, -98.2321689 27.753712, -98.2335819 27.754505, -98.2343609 27.754942, -98.2343609 27.754176, -98.2343649 27.752262, -98.2343509 27.751881, -98.2343249 27.751123, -98.2343249 27.751117, -98.2342979 27.750372, -98.2342959 27.750303, -98.2341909 27.748141, -98.2341549 27.747398, -98.2341499 27.747306, -98.2341369 27.747031, -98.2341329 27.74694, -98.2342779 27.746941, -98.2347129 27.746944, -98.2348579 27.746945, -98.2372289 27.746957, -98.2443439 27.746993, -98.2467159 27.747006, -98.2470359 27.747007, -98.2470289 27.747041, -98.2468419 27.748091, -98.2467799 27.748442, -98.2467449 27.748578, -98.2466399 27.748988, -98.2466059 27.749125, -98.2465649 27.749125, -98.2464419 27.749127, -98.2464019 27.749128, -98.2462229 27.749138, -98.2459529 27.749155, -98.2461409 27.749344, -98.2462679 27.749471, -98.2464499 27.74966, -98.2464219 27.749846, -98.2463679 27.750205, -98.2457849 27.75031, -98.2461659 27.750415, -98.2466009 27.750536, -98.2475449 27.750824, -98.2501459 27.751617))

**Comment by BathoryPeter** [comment]
@iamginpy: What was the tolerance parameter you have used in simplify() ? You get some error or an empty geometry?

**Comment by iamginpy** [comment]
$simplify = $polygon->simplify(0.01);
var_dump($simplify);

its giving me NULL result. I have already tried 1, 1.5 and 5. still null

**Comment by BathoryPeter** [comment]
Sorry, I forgot to mention that GeoPhp doesn't support simplify() natively, just with GEOS installed. See the docs: https://geophp.net/api.html

Please also note that if you are using geographical coordinates, the unit of tolerance parameter is in degrees. At 25˙ N its about one kilometer.

**Comment by mishal** [comment]
You can check my fork (https://github.com/mishal/GeoPHP) which would throw `UnsupportedException` for methods which require Geos php extension.
