### ISSUE TITLE
project Method is missing

### ISSUE THREAD

**Issue by kviolka** [phayes/geoPHP#50]
Hi,

i would like  to calculate some distances in meters with the GEOS extension. In the standard WGS84 projection the distance function returns no meters, but degrees. So I learned I have to project to a different SRID.

The project method is not implemented, any reason for this? Maybe I can supply a patch.

best,

Karsten

**Comment by TheCelavi** [comment]
@kviolka Dude, how do you project? Could you give me some sample code, I am obviously dumb... 

I have something like:

    $point1 = new \Point(10, 12);
    $point2 = new \Point(12, 10);

How to get distance in meters? How to invoke properly `project()` method? Thanks!

**Comment by BathoryPeter** [comment]
If you are using geographical coordinates (lat, lon) then greatCircleLength() is your friend: 

```
$line = new LineString([new Point(10, 12), new Point(12, 10)]);
echo $line->greatCircleLength();    // 311971.11435993 meters
echo $line->length();               // 2.828427 degree

**Comment by TheCelavi** [comment]
@BathoryPeter DUDE! You are awesome! Thanks! 

How about calculating shortest distance between two, per example, polygons? Is that possible? How to do that?

BTW, your recipe, as well as my second question -> I think that it should be part of the documentation, it is quite common...
